services:
  backend:
    image: aycha123/mon-dashboard-backend:latest
    # container_name: backend-api     ← Supprime cette ligne
    ports:
      - "5000:5000"
    restart: always

  frontend:
    image: aycha123/mon-dashboard-frontend:latest
    # container_name: frontend-app    ← Supprime cette ligne
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always