[frontend]
dashboard ansible_host=32.184.150.78 ansible_user=ubuntu ansible_ssh_private_key_file=/home/pfa/.jenkins/.ssh/key-devops.pem

[backend]
backend ansible_host=10.0.3.220 ansible_user=ubuntu ansible_ssh_private_key_file=/home/pfa/.jenkins/.ssh/key-devops.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyCommand="ssh -i /home/pfa/.jenkins/.ssh/key-devops.pem -W %h:%p -o StrictHostKeyChecking=no ubuntu@32.184.150.78"'