[defaults]
inventory = inventory.ini
remote_user = ubuntu
private_key_file = /home/pfa/.jenkins/.ssh/key-devops.pem
host_key_checking = False

[frontend]
dashboard ansible_host=44.230.178.61 ansible_user=ubuntu ansible_ssh_private_key_file=/home/pfa/.jenkins/.ssh/key-devops.pem

[backend]
backend ansible_host=10.0.3.96 ansible_user=ubuntu ansible_ssh_private_key_file=/home/pfa/.jenkins/.ssh/key-devops.pem