[frontend]
dashboard ansible_host=35.82.107.33 ansible_user=ubuntu ansible_ssh_private_key_file=/home/pfa/.jenkins/.ssh/new-key-devops.pem

[backend]
backend-server ansible_host=10.0.3.102 ansible_user=ubuntu ansible_ssh_private_key_file=/home/pfa/.jenkins/.ssh/new-key-devops.pem ansible_ssh_common_args='-o ProxyCommand="ssh -i /home/pfa/.jenkins/.ssh/new-key-devops.pem -W %h:%p -o StrictHostKeyChecking=no ubuntu@35.82.107.33"'