---
# =========================================================
# DEPLOY FRONTEND
# =========================================================
- name: Déployer le frontend React sur EC2
  hosts: frontend
  become: yes
  tasks:
    - name: Installer Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Démarrer Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Installer pip3
      apt:
        name: python3-pip
        state: present

    - name: Installer SDK Docker pour Python
      pip:
        name: docker
        state: present

    - name: Arrêter l'ancien container s'il existe
      docker_container:
        name: mon-dashboard-frontend
        state: absent
      ignore_errors: yes

    - name: Puller l'image depuis Docker Hub
      docker_image:
        name: aycha123/mon-dashboard-frontend:latest
        source: pull
        force_source: yes

    - name: Lancer le container React
      docker_container:
        name: mon-dashboard-frontend
        image: aycha123/mon-dashboard-frontend:latest
        state: started
        restart_policy: always
        ports:
          - "80:80"

    - name: Vérifier que le container tourne
      shell: docker ps | grep mon-dashboard-frontend
      register: result

    - name: Afficher le statut
      debug:
        msg: "✅ Frontend déployé : {{ result.stdout }}"

# =========================================================
# DEPLOY BACKEND
# =========================================================
- name: Déployer le backend Flask sur EC2
  hosts: backend
  become: yes
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ProxyCommand="ssh -i /home/pfa/.jenkins/.ssh/key-devops.pem -W %h:%p ubuntu@32.184.150.78"'
  tasks:
    - name: Installer Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Démarrer Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Installer pip3
      apt:
        name: python3-pip
        state: present

    - name: Installer SDK Docker pour Python
      pip:
        name: docker
        state: present

    - name: Arrêter l'ancien container s'il existe
      docker_container:
        name: mon-dashboard-backend
        state: absent
      ignore_errors: yes

    - name: Puller l'image depuis Docker Hub
      docker_image:
        name: aycha123/mon-dashboard-backend:latest
        source: pull
        force_source: yes

    - name: Récupérer AccessKeyId
      shell: curl -s http://169.254.169.254/latest/meta-data/iam/security-credentials/LabRole | python3 -c "import sys,json; print(json.load(sys.stdin)['AccessKeyId'])"
      register: aws_key_id

    - name: Récupérer SecretAccessKey
      shell: curl -s http://169.254.169.254/latest/meta-data/iam/security-credentials/LabRole | python3 -c "import sys,json; print(json.load(sys.stdin)['SecretAccessKey'])"
      register: aws_secret

    - name: Récupérer SessionToken
      shell: curl -s http://169.254.169.254/latest/meta-data/iam/security-credentials/LabRole | python3 -c "import sys,json; print(json.load(sys.stdin)['Token'])"
      register: aws_token

    - name: Lancer le container Flask
      docker_container:
        name: mon-dashboard-backend
        image: aycha123/mon-dashboard-backend:latest
        state: started
        restart_policy: always
        ports:
          - "5000:5000"
        env:
          MONGO_URI: "mongodb://10.0.5.88:27017/"
          AWS_DEFAULT_REGION: "us-west-2"
          AWS_ACCESS_KEY_ID: "{{ aws_key_id.stdout }}"
          AWS_SECRET_ACCESS_KEY: "{{ aws_secret.stdout }}"
          AWS_SESSION_TOKEN: "{{ aws_token.stdout }}"

    - name: Vérifier que le container tourne
      shell: docker ps | grep mon-dashboard-backend
      register: result

    - name: Afficher le statut
      debug:
        msg: "✅ Backend déployé : {{ result.stdout }}"